---
title: "someExamples"
author: "Dr K"
date: "September 11, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tigerstats)
require(tidyverse)
data(m111surveyfa12)
data(imagpop)
```

## look at the survey and imagepop


```{r }
View(m111surveyfa13)
View(imagpop)
```

## explore kkardashtemp in imagepop

You can also embed plots, for example:

```{r }
plot(imagpop$kkardashtemp)
hist(imagpop$kkardashtemp)
plot(density(imagpop$kkardashtemp))
```

## Try taking means of samples of size 2, size 3 and size 4 and look at the shapes of their distributions.


## Here is what you get for samples of size 2


```{r}
size2means=numeric()
for (i in 1:1000){
size2means[i] <-  mean(sample(imagpop$kkardashtemp,size=2))
}
plot(density(size2means))
```
Now we show an iteration  techinique

```{r}
require(purrr)
itlength=seq(1:1000)
size40means=numeric()
for (i in seq_along(itlength)){
  size40means[i]= mean(sample(imagpop$kkardashtemp,size=40))
}

plot(density(size40means))

```

# Homers addin for lattice graphics

```{r}
bwplot(GPA ~ love_first,
	data = m111surveyfa13)
```
#inferential test
```{r}
ttestGC(GPAlover_first,data=m111surveyfa13)
```
# ggplot2 is the tidyverse plot tool

```{r}
ggplot(data = m111surveyfa12) +
  geom_point(aes(x=height,y=sleep,col=sex))
```

